apiVersion : apps/v1
kind: Deployment
metadata:
  name: "khbobble"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "khbobble"
  template:
    metadata:
      labels:
        app: "khbobble"
    spec:
      containers:
        - name: "khbobble"
          image: "khaksacr.azurecr.io/khbobble"
          ports:
          - containerPort: 3000
